### ISSUE TITLE
With iPython 5.0 this copy-pastes code to iPython but doesn't execute.

### ISSUE THREAD

**Issue by CameronTStark** [julienr/vim-cellmode#13]
I wonder if there's a way to reconfigure ipython_config.py to get this to work?

**Comment by julienr** [comment]
I haven't had the chance to test with ipython 5 yet, but I'll try to do that next week.
I wonder what has changed. The plugin just simulates an "Enter" keypress in tmux.

Are you running ipython in tmux or screen ?

**Comment by CameronTStark** [comment]
I'm running it on tmux. Maybe there has to be two "Enter" keypresses...

**Comment by julienr** [comment]
Ok so the problem is that ipython 5 `%load` puts the cursor at the beginning of the source and you have to scroll all the way to the end to execute. We can't really reliably do that. So instead, I switched to using `%run` which seems to work fine with both ipython 5 and < 5.

The only downside is that you don't see the code you just executed in ipython's history, but just a line with `%run /tmp/foobar`. Not sure what we can do about that.

Anyway, can you checkout master and confirm that the bug is solved ?

**Comment by CameronTStark** [comment]
Confirmed working. Thanks for the quick response!

**Comment by julienr** [comment]
Great, thanks for the report !

**Comment by nilsbecker** [comment]
actually, using `%run` does not work for me. it seems that the environment inside run is different from what you would get with literal inclusion of code. for example, i load matplotlib  and to `from pylab import *` somewhere in the script and then do e.g. `figure(3)` to open a new figure. this does not work anymore since i upgraded vim-cellmode today.  this is on ipython 4.0.3

just for clarity, actually executing other code seems to work fine in general.

**Comment by nilsbecker** [comment]
maybe this answer could help?

http://stackoverflow.com/questions/34780275/how-do-i-combine-the-pylab-and-run-magic-commands-in-ipython

**Comment by nilsbecker** [comment]
hmm, i just saw it's already using -i. no idea then.

**Comment by nilsbecker** [comment]
> There is one special usage for which the text above doesn’t apply: if the filename ends with .ipy[nb], the file is run as ipython script, just as if the commands were written on IPython prompt.\

this is from the ipython docs. maybe renaming the temp files to '.ipy' would help?

**Comment by nilsbecker** [comment]
ok, so i checked by renaming. indeed renaming to the extension '.ipy' solved my problem. '.py' did not. '-i' option did not make a difference. so i would suggest adding '.ipy' to all temporary files.

**Comment by julienr** [comment]
@nilsbecker It's pretty strange because on my machine (OSX), it was working with ipython 4.0.1. Anyway, added the .ipy extension since it seems to work as well. Can you test master ? Thank you for digging into this !

**Comment by nilsbecker** [comment]
ok, i did PluginUpdate in vundle, restarted vim and indeed it works now -- i can spawn new matplotlib windows. i think it may have had to do with the event loop in some way. the only place where things did not work previously was making new mpl figures. anyway, it's fine now.

**Comment by julienr** [comment]
@nilsbecker Great, thanks for testing
