### ISSUE TITLE
Only Executes The First Cell

### ISSUE THREAD

**Issue by codemeleon** [julienr/vim-cellmode#22]
Hi,
When I try to run the code, it executes first cell only. I am using vim 8 on Ubuntu laptop.

**Comment by julienr** [comment]
I am not sure I understand correctly, but I think this is normal. The goal is to execute cells one by one. You can use `C-b` to execute a cell and move to the next one.
Otherwise, in the README there is an explanation on how to bind `C-a` to execute all cells above the one you're currently in with
```
noremap <silent> <C-a> :call RunTmuxPythonAllCellsAbove()<CR>
``` 

There isn't currently a function to execute all cells (well, you can select the whole file and do `C-c`), would that be what you want ?

**Comment by codemeleon** [comment]
Thanks. It has been resolved by adding empty cell at the end of the file.
